version: "3.6"
services:

  database:
    image: postgres:13.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]        
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  sensorasset:
    build:
      context: .
    env_file: ./.env
    depends_on:
      - database
    ports:
      - '8000:8000'